export enum EnvKey {
  PORT = 'PORT',
  DOCS_PATH = 'DOCS_PATH',
  BASE_PATH = 'BASE_PATH',
  CLIENT_BASE_URL = 'CLIENT_BASE_URL',

  COOKIE_AGE = 'COOKIE_AGE',
  TOKEN_SECRET = 'TOKEN_SECRET',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  ADMIN_EMAIL = 'ADMIN_EMAIL',
  ADMIN_PASSWORD = 'ADMIN_PASSWORD',
}
